// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWhYNMF7PkbZk60FD-mHzQOl9BCMChWNo',
    appId: '1:241461826546:web:aec1f0cf3f4f571745516b',
    messagingSenderId: '241461826546',
    projectId: 'leasure-nft-88aaf',
    authDomain: 'leasure-nft-88aaf.firebaseapp.com',
    storageBucket: 'leasure-nft-88aaf.firebasestorage.app',
    measurementId: 'G-H861Y6Y4LY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLr51tHYecaRibUtw1fsUNb9U3uZQR7Xg',
    appId: '1:241461826546:android:ffb498d91b512c6545516b',
    messagingSenderId: '241461826546',
    projectId: 'leasure-nft-88aaf',
    storageBucket: 'leasure-nft-88aaf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnkNewwIKujQTx3FXQ1A51mRX5JG6UX68',
    appId: '1:241461826546:ios:c8fd3d9c7c274d0f45516b',
    messagingSenderId: '241461826546',
    projectId: 'leasure-nft-88aaf',
    storageBucket: 'leasure-nft-88aaf.firebasestorage.app',
    iosBundleId: 'com.example.leasureNft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnkNewwIKujQTx3FXQ1A51mRX5JG6UX68',
    appId: '1:241461826546:ios:c8fd3d9c7c274d0f45516b',
    messagingSenderId: '241461826546',
    projectId: 'leasure-nft-88aaf',
    storageBucket: 'leasure-nft-88aaf.firebasestorage.app',
    iosBundleId: 'com.example.leasureNft',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWhYNMF7PkbZk60FD-mHzQOl9BCMChWNo',
    appId: '1:241461826546:web:ab739f15022a5fdf45516b',
    messagingSenderId: '241461826546',
    projectId: 'leasure-nft-88aaf',
    authDomain: 'leasure-nft-88aaf.firebaseapp.com',
    storageBucket: 'leasure-nft-88aaf.firebasestorage.app',
    measurementId: 'G-QY7270SYQH',
  );
}
